# Generated by Django 5.2.4 on 2025-07-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('buy_type', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
                ('placement', models.CharField(max_length=255)),
                ('cpu_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpu_type', models.CharField(max_length=10)),
                ('est_kpi', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('campaign_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
