# Generated by Django 5.2.4 on 2025-07-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['created_at']},
        ),
    ]
