# Generated by Django 5.2.4 on 2025-08-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_campaign_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='est_kpi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
