# Generated by Django 5.2.4 on 2025-08-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_campaign_est_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cpu_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='placement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
